// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwtTu-9MypFcyhMu7-FBDymJzv6DPrIC8',
    appId: '1:624389794325:web:8b5ec7b92296bde67f7c1c',
    messagingSenderId: '624389794325',
    projectId: 'safe-ship-34660',
    authDomain: 'safe-ship-34660.firebaseapp.com',
    storageBucket: 'safe-ship-34660.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbEz1cgLO5rJw_15fPLsmT4oPaKbFPKnA',
    appId: '1:624389794325:android:ef7faab2d7bc2b647f7c1c',
    messagingSenderId: '624389794325',
    projectId: 'safe-ship-34660',
    storageBucket: 'safe-ship-34660.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDotuL2o48tawq5tESthe0dFgIssQZwONU',
    appId: '1:624389794325:ios:8e972500dbb7f4397f7c1c',
    messagingSenderId: '624389794325',
    projectId: 'safe-ship-34660',
    storageBucket: 'safe-ship-34660.appspot.com',
    iosBundleId: 'com.example.safeShip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDotuL2o48tawq5tESthe0dFgIssQZwONU',
    appId: '1:624389794325:ios:8e972500dbb7f4397f7c1c',
    messagingSenderId: '624389794325',
    projectId: 'safe-ship-34660',
    storageBucket: 'safe-ship-34660.appspot.com',
    iosBundleId: 'com.example.safeShip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwtTu-9MypFcyhMu7-FBDymJzv6DPrIC8',
    appId: '1:624389794325:web:28d2d055a8ab58cd7f7c1c',
    messagingSenderId: '624389794325',
    projectId: 'safe-ship-34660',
    authDomain: 'safe-ship-34660.firebaseapp.com',
    storageBucket: 'safe-ship-34660.appspot.com',
  );
}
